"""Codex integration installers.

The initial Codex port intentionally mirrors the current Claude Code workflow:
skills and custom agents drive the same `hyperresearch ... --json` CLI backend.
MCP is not required for this parity path.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from pathlib import Path
from typing import Any

import yaml

from hyperresearch.core.hooks import (
    _HYPERRESEARCH_STEP_SKILLS,
    CORPUS_CRITIC_AGENT,
    DEPTH_CRITIC_AGENT,
    DEPTH_INVESTIGATOR_AGENT,
    DIALECTIC_CRITIC_AGENT,
    DRAFT_ORCHESTRATOR_AGENT,
    INSTRUCTION_CRITIC_AGENT,
    LOCI_ANALYST_AGENT,
    PATCHER_AGENT,
    POLISH_AUDITOR_AGENT,
    READABILITY_REFORMATTER_AGENT,
    RESEARCHER_AGENT,
    SOURCE_ANALYST_AGENT,
    SYNTHESIZER_AGENT,
    WIDTH_CRITIC_AGENT,
    _read_skill_source,
    _render_scaffold_only_bullets,
)

CODEX_SKILL_PREAMBLE = """
## Codex adapter notes

These instructions are adapted from the Claude Code hyperresearch workflow.
For initial parity, use the existing CLI backend, not MCP. Use this exact
binary path for every backend command; it may not be on PATH:

```bash
{hpr} ... --json
```

When these instructions say `Skill(skill: "hyperresearch-N-name")`, activate
the corresponding Codex skill, e.g. `$hyperresearch-N-name`, or explicitly load
that skill from `.agents/skills/hyperresearch-N-name/SKILL.md`.

When these instructions mention Claude `Task` subagents, use the corresponding
project-scoped Codex custom agent from `.codex/agents/*.toml` when available.
If a hard Claude tool lock cannot be represented exactly in Codex, obey the
prompt-level restriction and preserve the same artifact/log checks.

Do not use direct source-page browsing as a substitute for captured provenance.
Use `{hpr} fetch` for source pages.

## Mechanical Claude-to-Codex translations

The source skill text below remains the canonical workflow definition. When it
uses Claude Code terms, apply these translations mechanically:

- `Skill(skill: "hyperresearch-N-name")` means activate the Codex skill
  `$hyperresearch-N-name`, or load
  `.agents/skills/hyperresearch-N-name/SKILL.md`.
- `Task`, `Task tool`, `Task call`, or `subagent_type: NAME` means spawn the
  project-scoped Codex custom agent named `NAME` from `.codex/agents/NAME.toml`.
  When the step asks for multiple subagents in one message, spawn them in
  parallel in waves of at most 4 Codex custom agents. Wait for and close each
  completed wave before starting the next one, then consolidate all results
  before continuing.
- `TodoWrite` means maintain a visible Codex progress checklist and also write
  the same durable step state to `research/temp/orchestrator-progress.md`.
  Update both after every step; after compaction, recover from the progress
  file plus the canonical artifacts on disk.
- Claude model labels such as Opus/Sonnet are mapped in the generated
  `.codex/agents/*.toml` files. If a generated custom agent omits a model, it
  inherits the parent Codex session model.
- There is no `hyperresearch note create` command. Use
  `{hpr} note new ... --json` for new notes, preferably with `--body-file`
  when writing existing bodies, and `{hpr} note update ... --json` for metadata
  or body edits.
- Do not print full artifacts, large diffs, long JSON bodies, or final report
  drafts to stdout. Write artifacts to their required paths and report concise
  summaries, counts, and changed filenames. For inspection, prefer targeted
  `rg`, `jq`, `wc`, or `sed` snippets.

Do not edit generated Codex skills as the source of truth. Improve the bundled
Claude skill/subagent definitions, then rerun `{hpr} install --codex . --json`
to regenerate the Codex adapter files.

---
"""


CODEX_AGENT_PREAMBLE = """\
You are the Codex adaptation of a Hyperresearch Claude Code subagent.

Initial Codex parity uses the existing CLI backend, not MCP:
`hyperresearch ... --json`.

The original Claude metadata for this agent was:
- model: {model}
- tools: {tools}

If Codex cannot enforce the same tool surface exactly, treat the original tools
line as a behavioral restriction. In particular, agents that say Read + Edit
only must not regenerate whole files, run shell commands for unrelated work, or
write new draft files. Preserve patch logs, polish logs, and the existing
research artifact contract.

---

"""

CODEX_MODEL_MAP_RESOURCE = "codex_model_map.yaml"

CODEX_HOOK_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"Hyperresearch Codex hook guardrails.

Generated by `hyperresearch install --codex`. Do not edit directly; update
the installer in hyperresearch and regenerate.
\"\"\"

from __future__ import annotations

import json
import sys
from pathlib import Path

HPR = __HPR_JSON__


def _find_vault(start: str | None) -> Path | None:
    current = Path(start or ".").resolve()
    while True:
        if (current / ".hyperresearch").exists():
            return current
        parent = current.parent
        if parent == current:
            return None
        current = parent


def _message() -> str:
    return "\\n".join([
        "HYPERRESEARCH: A research knowledge base exists in this project.",
        "",
        "Before searching or fetching externally, check existing research:",
        f"  {HPR} search \\"<your query>\\" --json",
        "",
        "Do not ingest source pages directly when provenance matters.",
        f"Use: {HPR} fetch \\"<url>\\" --tag <topic> --json",
    ])


def _command_looks_like_direct_web_fetch(command: str) -> bool:
    lowered = command.lower()
    if "hyperresearch fetch" in lowered or " hpr fetch" in lowered:
        return False
    if "http://" not in lowered and "https://" not in lowered:
        return False
    web_fetch_markers = (
        "curl ",
        "wget ",
        "httpx",
        "urllib.request",
        "requests.get",
        "webfetch",
    )
    return any(marker in lowered for marker in web_fetch_markers)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        payload = {}

    vault = _find_vault(payload.get("cwd"))
    if vault is None:
        return 0

    event = payload.get("hook_event_name", "")
    if event == "SessionStart":
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SessionStart",
                "additionalContext": _message(),
            }
        }))
        return 0

    if event == "PreToolUse":
        tool_input = payload.get("tool_input") or {}
        command = str(tool_input.get("command") or "")
        if _command_looks_like_direct_web_fetch(command):
            print(json.dumps({
                "systemMessage": _message(),
            }))
        return 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""


@dataclass(frozen=True)
class CodexAgentSource:
    filename: str
    content: str
    label: str


def install_codex_workflow(vault_root: Path, hpr_path: str = "hyperresearch") -> list[str]:
    """Install Codex skills and custom agents for the hyperresearch workflow."""
    actions: list[str] = []
    for installer in (
        lambda: _install_codex_hooks(vault_root, hpr_path),
        lambda: _install_codex_entry_skill(vault_root, hpr_path),
        lambda: _install_codex_step_skills(vault_root, hpr_path),
        lambda: _install_codex_agents(vault_root, hpr_path),
    ):
        result = installer()
        if result:
            actions.append(result)
    return actions


def _install_codex_hooks(vault_root: Path, hpr_path: str) -> str | None:
    """Install repo-local Codex hook config and script."""
    changed: list[str] = []
    hook_dir = vault_root / ".codex" / "hooks"
    hook_dir.mkdir(parents=True, exist_ok=True)

    script_path = hook_dir / "hyperresearch_pre_tool_use.py"
    script = CODEX_HOOK_SCRIPT_TEMPLATE.replace(
        "__HPR_JSON__",
        json.dumps(hpr_path.replace("\\", "/")),
    )
    if not script_path.exists() or script_path.read_text(encoding="utf-8") != script:
        script_path.write_text(script, encoding="utf-8")
        changed.append(".codex/hooks/hyperresearch_pre_tool_use.py")

    hooks_path = vault_root / ".codex" / "hooks.json"
    hooks_config = _render_codex_hooks_json(script_path)
    if not hooks_path.exists() or hooks_path.read_text(encoding="utf-8") != hooks_config:
        hooks_path.write_text(hooks_config, encoding="utf-8")
        changed.append(".codex/hooks.json")

    config_path = vault_root / ".codex" / "config.toml"
    before = config_path.read_text(encoding="utf-8") if config_path.exists() else ""
    after = _ensure_codex_hooks_feature(before)
    if after != before:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(after, encoding="utf-8")
        changed.append(".codex/config.toml")

    if not changed:
        return None
    return f"Codex: hooks ({', '.join(changed)})"


def _render_codex_hooks_json(script_path: Path) -> str:
    command = f"python3 {_shell_quote(script_path.as_posix())}"
    config = {
        "hooks": {
            "SessionStart": [
                {
                    "matcher": "startup|resume",
                    "hooks": [
                        {
                            "type": "command",
                            "command": command,
                            "timeout": 30,
                            "statusMessage": "Loading hyperresearch guidance",
                        }
                    ],
                }
            ],
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {
                            "type": "command",
                            "command": command,
                            "timeout": 30,
                            "statusMessage": "Checking hyperresearch fetch policy",
                        }
                    ],
                }
            ],
        }
    }
    return json.dumps(config, indent=2) + "\n"


def _ensure_codex_hooks_feature(content: str) -> str:
    """Return config.toml content with current Codex hooks feature enabled."""
    if not content.strip():
        return "[features]\nhooks = true\n"

    lines = content.splitlines()
    features_start: int | None = None
    features_end = len(lines)
    for idx, line in enumerate(lines):
        if re.match(r"^\s*\[features\]\s*$", line):
            features_start = idx
            continue
        if features_start is not None and idx > features_start and re.match(r"^\s*\[[^\]]+\]\s*$", line):
            features_end = idx
            break

    if features_start is None:
        suffix = "\n" if content.endswith("\n") else "\n\n"
        return f"{content}{suffix}[features]\nhooks = true\n"

    hooks_idx: int | None = None
    legacy_idxs: list[int] = []
    for idx in range(features_start + 1, features_end):
        if re.match(r"^\s*hooks\s*=", lines[idx]):
            hooks_idx = idx
        elif re.match(r"^\s*codex_hooks\s*=", lines[idx]):
            legacy_idxs.append(idx)

    if hooks_idx is not None:
        lines[hooks_idx] = "hooks = true"
        for idx in reversed(legacy_idxs):
            del lines[idx]
        return "\n".join(lines) + "\n"

    if legacy_idxs:
        first = legacy_idxs[0]
        lines[first] = "hooks = true"
        for idx in reversed(legacy_idxs[1:]):
            del lines[idx]
        return "\n".join(lines) + "\n"

    lines.insert(features_start + 1, "hooks = true")
    return "\n".join(lines) + "\n"


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _install_codex_entry_skill(vault_root: Path, hpr_path: str) -> str | None:
    content = _read_skill_source("hyperresearch.md")
    if content is None:
        return None
    return _write_codex_skill(vault_root, "hyperresearch", _adapt_codex_skill(content, hpr_path))


def _install_codex_step_skills(vault_root: Path, hpr_path: str) -> str | None:
    installed: list[str] = []
    for skill_name in _HYPERRESEARCH_STEP_SKILLS:
        content = _read_skill_source(f"{skill_name}.md")
        if content is None:
            continue
        result = _write_codex_skill(vault_root, skill_name, _adapt_codex_skill(content, hpr_path))
        if result:
            installed.append(skill_name)

    if not installed:
        return None
    return f"Codex: .agents/skills/hyperresearch-N-*/SKILL.md ({len(installed)} step skills)"


def _write_codex_skill(vault_root: Path, skill_name: str, content: str) -> str | None:
    skill_dir = vault_root / ".agents" / "skills" / skill_name
    skill_dir.mkdir(parents=True, exist_ok=True)
    dest_path = skill_dir / "SKILL.md"
    if dest_path.exists() and dest_path.read_text(encoding="utf-8") == content:
        return None
    dest_path.write_text(content, encoding="utf-8")
    return f"Codex: .agents/skills/{skill_name}/SKILL.md"


def _adapt_codex_skill(content: str, hpr_path: str) -> str:
    hpr_posix = hpr_path.replace("\\", "/")
    content = content.replace(".claude/skills", ".agents/skills")
    content = content.replace("{hpr_path}", hpr_posix)
    content = content.replace("hyperresearch init . --json", f"{hpr_posix} init . --json")
    content = content.replace("hyperresearch install --steps-only . --json", f"{hpr_posix} install --codex . --json")
    content = content.replace("hyperresearch note show <id1> <id2> ... -j", f"{hpr_posix} note show <id1> <id2> ... -j")
    content = content.replace("hyperresearch note create", f"{hpr_posix} note new")
    content = _translate_codex_todo_terms(content)
    preamble = CODEX_SKILL_PREAMBLE.format(hpr=hpr_posix)
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) == 3:
            return f"---{parts[1]}---\n\n{preamble}\n{parts[2].lstrip()}"
    return f"{preamble}\n{content}"


def _translate_codex_todo_terms(content: str) -> str:
    """Translate common Claude workflow terms to Codex execution wording."""
    replacements = {
        "Task results": "subagent results",
        "Task result": "subagent result",
        "Task prompt": "subagent prompt",
        "Task calls": "Codex custom-agent spawns",
        "Task call": "Codex custom-agent spawn",
        "Task tool": "Codex custom-agent spawning",
        "TodoWrite list": "Codex progress checklist and `research/temp/orchestrator-progress.md`",
        "TodoWrite": "Codex progress checklist",
        "todo list": "progress checklist",
        "todos": "progress items",
    }
    for source, target in replacements.items():
        content = content.replace(source, target)
    return content


def _install_codex_agents(vault_root: Path, hpr_path: str) -> str | None:
    installed: list[str] = []
    for source in _codex_agent_sources(hpr_path):
        result = _write_codex_agent(vault_root, source)
        if result:
            installed.append(source.filename)
    if not installed:
        return None
    return f"Codex: .codex/agents/*.toml ({len(installed)} agents)"


def _codex_agent_sources(hpr_path: str) -> list[CodexAgentSource]:
    hpr_posix = hpr_path.replace("\\", "/")
    return [
        CodexAgentSource("hyperresearch-fetcher.toml", RESEARCHER_AGENT.format(hpr_path=hpr_posix), "fetcher"),
        CodexAgentSource("hyperresearch-loci-analyst.toml", LOCI_ANALYST_AGENT.format(hpr_path=hpr_posix), "loci analyst"),
        CodexAgentSource("hyperresearch-depth-investigator.toml", DEPTH_INVESTIGATOR_AGENT.format(hpr_path=hpr_posix), "depth investigator"),
        CodexAgentSource("hyperresearch-source-analyst.toml", SOURCE_ANALYST_AGENT.format(hpr_path=hpr_posix), "source analyst"),
        CodexAgentSource("hyperresearch-corpus-critic.toml", CORPUS_CRITIC_AGENT.replace("{hpr_path}", hpr_posix), "corpus critic"),
        CodexAgentSource("hyperresearch-draft-orchestrator.toml", DRAFT_ORCHESTRATOR_AGENT.replace("{hpr_path}", hpr_posix), "draft orchestrator"),
        CodexAgentSource("hyperresearch-synthesizer.toml", SYNTHESIZER_AGENT, "synthesizer"),
        CodexAgentSource("hyperresearch-dialectic-critic.toml", DIALECTIC_CRITIC_AGENT.format(hpr_path=hpr_posix), "dialectic critic"),
        CodexAgentSource("hyperresearch-depth-critic.toml", DEPTH_CRITIC_AGENT.format(hpr_path=hpr_posix), "depth critic"),
        CodexAgentSource("hyperresearch-width-critic.toml", WIDTH_CRITIC_AGENT.format(hpr_path=hpr_posix), "width critic"),
        CodexAgentSource("hyperresearch-instruction-critic.toml", INSTRUCTION_CRITIC_AGENT, "instruction critic"),
        CodexAgentSource("hyperresearch-patcher.toml", PATCHER_AGENT, "patcher"),
        CodexAgentSource(
            "hyperresearch-polish-auditor.toml",
            POLISH_AUDITOR_AGENT.format(scaffold_only_sections=_render_scaffold_only_bullets(indent="- ")),
            "polish auditor",
        ),
        CodexAgentSource("hyperresearch-readability-recommender.toml", READABILITY_REFORMATTER_AGENT, "readability recommender"),
    ]


def _write_codex_agent(vault_root: Path, source: CodexAgentSource) -> str | None:
    agents_dir = vault_root / ".codex" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    dest_path = agents_dir / source.filename
    content = _render_codex_agent_toml(source.content)
    if dest_path.exists() and dest_path.read_text(encoding="utf-8") == content:
        return None
    dest_path.write_text(content, encoding="utf-8")
    return f"Codex: .codex/agents/{source.filename} ({source.label})"


def _render_codex_agent_toml(agent_markdown: str) -> str:
    meta, body = _split_claude_agent(agent_markdown)
    name = str(meta.get("name", "hyperresearch-agent"))
    description = str(meta.get("description", "Hyperresearch Codex custom agent.")).strip()
    model = str(meta.get("model", "parent"))
    tools = str(meta.get("tools", "parent"))
    sandbox_mode = _sandbox_for_tools(tools)
    developer_instructions = CODEX_AGENT_PREAMBLE.format(model=model, tools=tools) + body.strip() + "\n"
    codex_model, reasoning_effort = _codex_model_for_claude_model(model)

    lines = [
        f"name = {_toml_string(name)}",
        f"description = {_toml_string(description)}",
        *([f"model = {_toml_string(codex_model)}"] if codex_model else []),
        *([f"model_reasoning_effort = {_toml_string(reasoning_effort)}"] if reasoning_effort else []),
        f"sandbox_mode = {_toml_string(sandbox_mode)}",
        f"developer_instructions = {_toml_string(developer_instructions)}",
        "",
    ]
    return "\n".join(lines)


@lru_cache(maxsize=1)
def _load_codex_model_map() -> dict[str, tuple[str, str | None]]:
    """Load project policy for Claude-label to Codex-model translation."""
    resource = resources.files("hyperresearch").joinpath(CODEX_MODEL_MAP_RESOURCE)
    raw = yaml.safe_load(resource.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        return {}

    model_map: dict[str, tuple[str, str | None]] = {}
    for claude_label, codex_settings in raw.items():
        if not isinstance(claude_label, str) or not isinstance(codex_settings, dict):
            continue
        model = codex_settings.get("model")
        reasoning_effort = codex_settings.get("model_reasoning_effort")
        if not isinstance(model, str) or not model:
            continue
        if not isinstance(reasoning_effort, str) or not reasoning_effort:
            reasoning_effort = None
        model_map[claude_label.lower()] = (model, reasoning_effort)
    return model_map


def _codex_model_for_claude_model(model: str) -> tuple[str | None, str | None]:
    mapped = _load_codex_model_map().get(model.lower())
    if mapped is None:
        return None, None
    return mapped


def _split_claude_agent(agent_markdown: str) -> tuple[dict[str, Any], str]:
    if not agent_markdown.startswith("---"):
        return {}, agent_markdown
    parts = agent_markdown.split("---", 2)
    if len(parts) != 3:
        return {}, agent_markdown
    meta = yaml.safe_load(parts[1]) or {}
    if not isinstance(meta, dict):
        meta = {}
    return meta, parts[2]


def _sandbox_for_tools(tools: str) -> str:
    normalized = {part.strip().lower() for part in tools.split(",")}
    if normalized and normalized <= {"read"}:
        return "read-only"
    if "write" in normalized or "edit" in normalized:
        return "workspace-write"
    return "read-only"


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
